- name: Configuring Controller Node
  hosts: [controllers] 
  user: ubuntu

  vars_prompt:
    - name: cni_choice
      prompt: "Choose Container Network Interface (CNI) to Install (calico or  weave): "
      default: "weave"
      private: no

  tasks:
  - name: Setting Deployment Variables
    include_vars: deployment_vars.yaml

  - name: Checking if Kubernetes admin.conf is Present
    stat:
      path: /etc/kubernetes/admin.conf
    register: file_details

  - name: Initializing Kubernetes Cluster with kubeadm init
    shell:
      cmd: "kubeadm init --image-repository {{image_repo}} --apiserver-advertise-address={{controller_ip}} --apiserver-bind-port={{controller_port}} --kubernetes-version v{{k8s_version}} --pod-network-cidr={{pod_nw_cidr}}"
    become: yes
    when: file_details.stat.exists == false

  - name: Creating .kube Directory to Hold User Configuration & Cluster Contexts
    file:
      path: /home/ubuntu/.kube
      state: directory

  - name: Copying admin.conf to /home/ubuntu/.kube/config
    copy:
      src: /etc/kubernetes/admin.conf
      dest: /home/ubuntu/.kube/config
      remote_src: yes
      owner: ubuntu
      group: ubuntu
      mode: 400
    become: yes

  - name: Installing WeaveNet Container Network Interface
    shell:
      cmd: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
    when: cni_choice == "weave"

  - name: Installing Calico Container Network Interface
    shell:
      cmd: kubectl apply -f https://docs.projectcalico.org/v3.14/getting-started/kubernetes/installation/hosted/calico.yaml
    when: cni_choice == "calico"

  - name: Generating Cluster Join Command Token for Worker Nodes
    shell: kubeadm token create --print-join-command
    register: join_command
  - name: Copying Cluster Token to Ansible Control Node
    local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"

  - name: Adding GPG Key for HashiCorp apt Repository
    apt_key:
      url: https://apt.releases.hashicorp.com/gpg
      state: present
    become: true
  - name: Adding HashiCorp apt Repository
    apt_repository:
      repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{distro_codename}} main"
      state: present
      update_cache: true
    become: true
  - name: Installing Latest HashiCorp Consul Release
    apt:
      name: consul
      state: latest
    become: true

  - name: Adding GPG Key Helm apt Repository
    apt_key:
      url: https://baltocdn.com/helm/signing.asc
      state: present
    become: true
  - name: Adding Helm Package Manager Repository
    apt_repository:
      repo: deb https://baltocdn.com/helm/stable/debian/ all main
      state: present
      update_cache: true
    become: true
  - name: Installing Latest Helm Release
    apt:
      name: helm
      state: latest
    become: true
  - name: Adding Helm Repositories
    community.kubernetes.helm_repository:
      name: "{{item.name}}"
      repo_url: "{{item.repo_url}}"
    with_items:
      - {name: 'stable',repo_url: 'https://charts.helm.sh/stable'}
      - {name: 'hashicorp',repo_url: 'https://helm.releases.hashicorp.com'}
      - {name: 'bitnami',repo_url: 'https://charts.bitnami.com/bitnami'}


# TO DO: Add logic to choose CNI
#  - name: Install calico pod network
#      become: false
#          command: kubectl create -f https://docs.projectcalico.org/v3.4/getting-started/kubernetes/installation/hosted/calico.yaml
