distro_id: Ubuntu
distro_codename: bionic
#join_token: ayngk7.m1555duk5x2i3ctt
controller_ip: 172.16.60.100
controller_port: 8443
k8s_version: 1.19.3
#k8s_apt_version: 1.19.3-00
pod_nw_cidr: 10.244.0.0/16
image_repo: k8s.gcr.io
kubelet_ip: "$(/sbin/ip -o -4 addr list ens192 | awk '{print $4}' | cut -d/ -f1)"
