apiVersion: batch/v1
kind: Job
metadata:
  name: kube-hunter
  labels:
    app: aquasec-kube-hunter
spec:
  template:
    spec:
      containers:
      - name: kube-hunter
        image: aquasec/kube-hunter
        command: ["kube-hunter"]
        args: ["--pod"]
      restartPolicy: Never
  backoffLimit: 4
